<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MealSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $meals = [
            [
                'category_id'    => 3,
                'store_id'       => 2,
                'name_en'        => 'Cheese Burger',
                'name_ar'        => 'برجر بالجبنة',
                'description_en' => 'Delicious grilled beef burger',
                'description_ar' => 'برجر لحم مشوي',
                'image'          => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd',
                'price'          => 10,
                'sale_price'     => 8,
            ],
            [
                'category_id'    => 3,
                'store_id'       => 2,
                'name_en'        => 'Pizza',
                'name_ar'        => 'بيتزا',
                'description_en' => 'Italian pizza',
                'description_ar' => 'بيتزا ايطالي',
                'image'          => 'https://images.unsplash.com/photo-1601924582975-7e8f9d1fefc3',
                'price'          => 12,
                'sale_price'     => 10,
            ],
            [
                'category_id'    => 3,
                'store_id'       => 2,
                'name_en'        => 'Fried Chicken',
                'name_ar'        => 'فراخ مقلية',
                'description_en' => 'Crispy fried chicken',
                'description_ar' => 'دجاج مقلي مقرمش',
                'image'          => 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58',
                'price'          => 14,
                'sale_price'     => 12,
            ],
            [
                'category_id'    => 3,
                'store_id'       => 2,
                'name_en'        => 'Pasta',
                'name_ar'        => 'باستا',
                'description_en' => 'Creamy pasta',
                'description_ar' => 'مكرونة بصوص كريمي',
                'image'          => 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb',
                'price'          => 11,
                'sale_price'     => 9,
            ],
            [
                'category_id'    => 4,
                'store_id'       => 2,
                'name_en'        => 'Cheese Burger',
                'name_ar'        => 'برجر بالجبنة',
                'description_en' => 'Delicious grilled beef burger',
                'description_ar' => 'برجر لحم مشوي',
                'image'          => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd',
                'price'          => 10,
                'sale_price'     => 8,
            ],
            [
                'category_id'    => 4,
                'store_id'       => 2,
                'name_en'        => 'Pizza',
                'name_ar'        => 'بيتزا',
                'description_en' => 'Italian pizza',
                'description_ar' => 'بيتزا ايطالي',
                'image'          => 'https://images.unsplash.com/photo-1601924582975-7e8f9d1fefc3',
                'price'          => 12,
                'sale_price'     => 10,
            ],
            [
                'category_id'    => 4,
                'store_id'       => 2,
                'name_en'        => 'Fried Chicken',
                'name_ar'        => 'فراخ مقلية',
                'description_en' => 'Crispy fried chicken',
                'description_ar' => 'دجاج مقلي مقرمش',
                'image'          => 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58',
                'price'          => 14,
                'sale_price'     => 12,
            ],
            [
                'category_id' => 4,
                'store_id' => 2,
                'name_en'        => 'Pasta',
                'name_ar'        => 'باستا',
                'description_en' => 'Creamy pasta',
                'description_ar' => 'مكرونة بصوص كريمي',
                'image'          => 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb',
                'price'          => 11,
                'sale_price'     => 9,
            ],
            [
                'category_id' => 5,
                'store_id' => 2,
                'name_en'        => 'Cheese Burger',
                'name_ar'        => 'برجر بالجبنة',
                'description_en' => 'Delicious grilled beef burger',
                'description_ar' => 'برجر لحم مشوي',
                'image'          => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd',
                'price'          => 10,
                'sale_price'     => 8,
            ],
            [
                'category_id' => 5,
                'store_id' => 2,
                'name_en'        => 'Pizza',
                'name_ar'        => 'بيتزا',
                'description_en' => 'Italian pizza',
                'description_ar' => 'بيتزا ايطالي',
                'image'          => 'https://images.unsplash.com/photo-1601924582975-7e8f9d1fefc3',
                'price'          => 12,
                'sale_price'     => 10,
            ],
            [
                'category_id' => 5,
                'store_id' => 2,
                'name_en'        => 'Fried Chicken',
                'name_ar'        => 'فراخ مقلية',
                'description_en' => 'Crispy fried chicken',
                'description_ar' => 'دجاج مقلي مقرمش',
                'image'          => 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58',
                'price'          => 14,
                'sale_price'     => 12,
            ],
            [
                'category_id' => 5,
                'store_id' => 2,
                'name_en'        => 'Pasta',
                'name_ar'        => 'باستا',
                'description_en' => 'Creamy pasta',
                'description_ar' => 'مكرونة بصوص كريمي',
                'image'          => 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb',
                'price'          => 11,
                'sale_price'     => 9,
            ],
            [
                'category_id' => 5,
                'store_id' => 2,
                'name_en'        => 'Cheese Burger',
                'name_ar'        => 'برجر بالجبنة',
                'description_en' => 'Delicious grilled beef burger',
                'description_ar' => 'برجر لحم مشوي',
                'image'          => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd',
                'price'          => 10,
                'sale_price'     => 8,
            ],
            [
               'category_id' => 6,
                'store_id' => 2,
                'name_en'        => 'Pizza',
                'name_ar'        => 'بيتزا',
                'description_en' => 'Italian pizza',
                'description_ar' => 'بيتزا ايطالي',
                'image'          => 'https://images.unsplash.com/photo-1601924582975-7e8f9d1fefc3',
                'price'          => 12,
                'sale_price'     => 10,
            ],
            [
                'category_id' => 6,
                'store_id' => 2,
                'name_en'        => 'Fried Chicken',
                'name_ar'        => 'فراخ مقلية',
                'description_en' => 'Crispy fried chicken',
                'description_ar' => 'دجاج مقلي مقرمش',
                'image'          => 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58',
                'price'          => 14,
                'sale_price'     => 12,
            ],
            [
                 'category_id' => 6,
                'store_id' => 2,
                'name_en'        => 'Pasta',
                'name_ar'        => 'باستا',
                'description_en' => 'Creamy pasta',
                'description_ar' => 'مكرونة بصوص كريمي',
                'image'          => 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb',
                'price'          => 11,
                'sale_price'     => 9,
            ],
            [
                 'category_id' => 6,
                'store_id' => 2,
                'name_en'        => 'Cheese Burger',
                'name_ar'        => 'برجر بالجبنة',
                'description_en' => 'Delicious grilled beef burger',
                'description_ar' => 'برجر لحم مشوي',
                'image'          => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd',
                'price'          => 10,
                'sale_price'     => 8,
            ],
            [
                 'category_id' => 6,
                'store_id' => 2,
                'name_en'        => 'Pizza',
                'name_ar'        => 'بيتزا',
                'description_en' => 'Italian pizza',
                'description_ar' => 'بيتزا ايطالي',
                'image'          => 'https://images.unsplash.com/photo-1601924582975-7e8f9d1fefc3',
                'price'          => 12,
                'sale_price'     => 10,
            ],
            [ 
                'category_id' => 7,
                'store_id' => 2,
                'name_en'        => 'Fried Chicken',
                'name_ar'        => 'فراخ مقلية',
                'description_en' => 'Crispy fried chicken',
                'description_ar' => 'دجاج مقلي مقرمش',
                'image'          => 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58',
                'price'          => 14,
                'sale_price'     => 12,
            ],
            [
                'category_id' => 7,
                'store_id' => 2,
                'name_en'        => 'Pasta',
                'name_ar'        => 'باستا',
                'description_en' => 'Creamy pasta',
                'description_ar' => 'مكرونة بصوص كريمي',
                'image'          => 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb',
                'price'          => 11,
                'sale_price'     => 9,
            ],
        ];

        DB::table('meals')->insert($meals);
    }
}
